name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_USERNAME}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${DOCKER_USERNAME}/person_detection_service:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${DOCKER_USERNAME}/person_detection_service:latest
